Traceback (most recent call last):
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/sjt972/anaconda3/envs/poli-docs-310/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from poli.core.registry import register_observer
from poli.core.util.observers.mlflow_observer import MLFlowObserver

register_observer(
    observer=MLFlowObserver(),
    # conda_environment_location="poli",  # when not providing the environment, we use the current one
    observer_name="mlflow_observer",
    set_as_default_observer=False,  # this is True by default!
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpoli[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mregistry[39;00m [38;5;28;01mimport[39;00m register_observer
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpoli[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m[38;5;21;01m.[39;00m[38;5;21;01mobservers[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmlflow_observer[39;00m [38;5;28;01mimport[39;00m MLFlowObserver
[1;32m      4[0m register_observer(
[1;32m      5[0m     observer[38;5;241m=[39mMLFlowObserver(),
[1;32m      6[0m     [38;5;66;03m# conda_environment_location="poli",  # when not providing the environment, we use the current one[39;00m
[1;32m      7[0m     observer_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mmlflow_observer[39m[38;5;124m"[39m,
[1;32m      8[0m     set_as_default_observer[38;5;241m=[39m[38;5;28;01mFalse[39;00m,  [38;5;66;03m# this is True by default![39;00m
[1;32m      9[0m )

[0;31mModuleNotFoundError[0m: No module named 'poli.core.util.observers'

